README.md
hey @tyleryasaka just a minor name correction
=> control script name correction in README.md

README.md, bridge.md, container/files/scripts/start-bridge-server.sh
@sparrowDom I think this will take care of the Postgres insert error you were getting? https://github.com/OriginProtocol/origin-box/issues/6
=> Bridge server tweaks

README.md, bridge.md, container/Dockerfile, container/files/config/bridge_dev.env, container/files/process.json, container/files/scripts/start-bridge.sh, docker-compose.yml, scripts/setup.sh
Two of our repo names changed:
- bridge-server -> origin-bridge
- demo-dapp -> origin-dapp
=> Update repo names

docker-compose.yml
Just a few little updates, mostly to make things a bit faster.
=> Minor changes

docker-compose.yml
Add Apollo server port forward, for developers to access playground.
=> Add port forward 

README.md
=> add a troubleshooting step if Docker is failing with exit code 137

README.md
Added hyperlinks to Docker and Git requirements. Fixed a typo or two.
=> Typo and UX tweaks

dockerfiles/elasticsearch
Add indexes for listings documents in elastic search
Dependant PRs: 
- https://github.com/OriginProtocol/origin-js/pull/458
- https://github.com/OriginProtocol/origin-dapp/pull/503
=> Elasticsearch index

docker-compose-test.yml
- Added `npm install` to startup for `origin-js-test`
- Removed unused postgresql container
=> Ensure tests install npm packages for origin-js

deployment/dockerfiles/staging/origin-dapp
Should have been staging not stable. 😬
=> Fix branch used in origin-dapp staging container

development/dockerfiles/elasticsearch
add status index to listings in elasticsearch
Connected PR: https://github.com/OriginProtocol/origin-js/pull/502
=> add status index to listings in elasticsearch

deployment/DEPLOYMENT.md, deployment/deploy.sh, deployment/kubernetes/charts/origin/templates/discovery.ingress.yaml
- Make sed work on both OS X and Linux
- Fix bad port
- Add some more documentation
- Handle decryption failure better
=> Deployment fixes

deployment/kubernetes/values/values-staging.yaml
For deployment I ran this afternoon...
=> Container image tags for v0.8.0

deployment/kubernetes/charts/origin/scripts/start-event-listener.sh, deployment/kubernetes/charts/origin/templates/eventlistener.deployment.yaml, deployment/kubernetes/values/values-staging.yaml
Adds a continue file for event listener at 3m, Origin epoch on Rinkeby! No persistence yet.
=> Add continue block to event listener

deployment/kubernetes/charts/origin/templates/messaging.statefulset.yaml
Fix for new messaging namespace scheme.
=> Update messaging namespaces

deployment/kubernetes/charts/origin/templates/bridge.deployment.yaml
This is required for attestations to work properly.
=> Add env vars for bridge host and https

deployment/kubernetes/values/values-dev.yaml, deployment/kubernetes/values/values-prod.yaml, deployment/kubernetes/values/values-staging.yaml
Fix for https://github.com/OriginProtocol/origin-dapp/issues/548 until we get sticky sessions.
=> Use single replica for bridge due to no sticky sessions

deployment/deploy.sh
=> Fix writing of deploy tag to value files

origin-messaging/src/config.js, origin-messaging/src/index.js
Allows configuration of where IPFS stores its data for js-ipfs.
=> Make IPFS repo path configurable

origin-messaging/src/config.js, origin-messaging/src/index.js
Makes it possible to configure where OrbitDB stores its data.
=> Make Orbit DB data path configurable

deployment/dockerfiles/dev/origin-dapp, deployment/dockerfiles/prod/origin-dapp, deployment/dockerfiles/staging/origin-dapp
To go along with this PR: https://github.com/OriginProtocol/origin-dapp/pull/601
=> Setting `ETH_NETWORK_ID` env var

deployment/kubernetes/charts/origin/templates/eventlistener.deployment.yaml
Fix value name for database instance.
=> Fix database instance reference

deployment/kubernetes/values/values-prod.yaml
Updated bridge and epoch for event listener.
=> Deployment values

deployment/dockerfiles/dev/origin-dapp, deployment/dockerfiles/prod/origin-dapp, deployment/dockerfiles/staging/origin-dapp, development/envfiles/origin-dapp.env
Companion to OriginProtocol/origin-dapp#656
=> Add BLOCK_EPOCH to various environments

deployment/kubernetes/charts/origin/templates/messaging.ingress.yaml
Tweak the nginx settings for messaging. @franckc please merge this in before the next deployments. :smile:
=> Change messaging proxy_buffer settings
